version: '3.8'

services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe_wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wp-data:/var/www/html
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cafe_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=somewordpress

volumes:
  db_data:
